### ISSUE TITLE
[ASK] How to return exception to function

### ISSUE THREAD

**Issue by ad3n** [tommie/v8go#65]
I check the signature of function always return ```*v8go.Value``` and ```error```, is it possible to return exception or how to trigger exception from function?

**Comment by ad3n** [comment]
https://github.com/tommie/v8go/blob/v0.12.0/isolate.go#L154

Could i use this function?

**Comment by tommie** [comment]
You can use that, yes.

This fork makes it possible to, instead, return an error: https://pkg.go.dev/github.com/tommie/v8go#NewError

Like in this test:

https://github.com/tommie/v8go/blob/99f7408b99acc38b62a0b34ac33de4c53abc0070/function_template_test.go#L156-L158
